SearchingBox was added to Map Component,  not generated correctly
FAIRit/fe-where-is-fav-marketplace pull request #31
Opened 2020-04-03 14:56 UTC by Szpadzik

2020-04-08 16:07 UTC, michalczukm requested changes
Please fix this stuff about navigation

2020-04-08 16:07 UTC, michalczukm commented on src/components/Detail.js
> +
```jsx
navigateToBlock = (block) => {
    this.props.history.push(`../${block.name}`);
}
```

2020-04-08 16:07 UTC, michalczukm commented on src/components/Detail.js
> +                        <button className="BackButton"
`<button className="BackButton" onClick={this.navigateToBlock.bind(this, block)}>X</button>`

2020-04-08 16:07 UTC, michalczukm commented on src/components/SearchingMap.js
> +        const provider = new OpenStreetMapProvider();
From what I see we can use `customProvider`
![Screenshot 2020-04-08 at 18 05 09](https://user-images.githubusercontent.com/6861120/78806949-ad390400-79c3-11ea-9625-6de8e3be9ad7.png)

2020-04-11 20:35 UTC, michalczukm commented
Waiting fo changes, @Szpadzik please ping me when you push them ;)

2020-04-14 14:36 UTC, Szpadzik commented
@michalczukm, i've corrected the method for back button, now i want to merge my all branches (firebase and search).

2020-04-14 21:54 UTC, michalczukm approved these changes

2020-04-15 08:59 UTC, merged